// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// A08 — l'URL et la clé publiable proviennent de l'environnement (.env),
// jamais du code source. Les valeurs de repli existent uniquement pour ne pas
// casser un environnement d'aperçu où les variables ne seraient pas injectées.
const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined) ??
  "https://piyvinbuxpnquwzyugdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ??
  "";

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Configuration Supabase manquante : définissez VITE_SUPABASE_PUBLISHABLE_KEY dans votre fichier .env",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});