// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piyvinbuxpnquwzyugdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeXZpbmJ1eHBucXV3enl1Z2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDAzMDMsImV4cCI6MjA3MTExNjMwM30.khqzhiITwYsgbZBVI5X-zIVeGkNOD6tGy8eQaCU-k4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});